### ISSUE TITLE
design schedule

### ISSUE THREAD

**Issue by Schmitt-Florian** [Schmitt-Florian/SchoolPlanner#17]
todo

**Comment by Schmitt-Florian** [comment]
won't u going to do a special app bar?

**Comment by DWolkewitz** [comment]
Yeah, do you know how I can set the specialised toolbar only for the schedule?
Darius WolkewitzAm 06.06.17, 18:44, Schmitt-Florian <notifications@github.com> schrieb:
won't u going to do a special app bar?

**Comment by Schmitt-Florian** [comment]
no, but some googling should do it for you

**Comment by Schmitt-Florian** [comment]
you found a great work arount, but could you even specifiy where the crashing happens?
And please please use a SwitchCompat instead of the toogle button.

**Comment by Schmitt-Florian** [comment]
i'm sorry to tell you, but it just looks like $#!%, that even the last version was way better

**Comment by Schmitt-Florian** [comment]
Made an alternative version of the app bar. What do you think?

**Comment by Schmitt-Florian** [comment]
adding Periods and Lessons to the Schedule makes it look awful, b/c the size of the fields may not fit. Would be great if you could find a soultion for it

**Comment by DWolkewitz** [comment]
Put abbreviations into it
Darius WolkewitzAm 15.06.17, 18:22, Schmitt-Florian <notifications@github.com> schrieb:
adding Periods and Lessons to the Schedule makes it look awful, b/c the size of the fields may not fit. Would be great if you could find a soultion for it

**Comment by Schmitt-Florian** [comment]
how should i abbreviate a time ?

**Comment by DWolkewitz** [comment]
Demete it, doesn't really matter anyway
Darius WolkewitzAm 15.06.17, 22:27, Schmitt-Florian <notifications@github.com> schrieb:
how should i abbreviate a time ?

**Comment by Schmitt-Florian** [comment]
have you seen it?

**Comment by DWolkewitz** [comment]
No but I will check it now, sorry that I didn't do anything in recent days :/ I was occupied with Bigband...
Darius WolkewitzAm 15.06.17, 23:19, Schmitt-Florian <notifications@github.com> schrieb:
have you seen it?

**Comment by Schmitt-Florian** [comment]
ok

**Comment by DWolkewitz** [comment]
I am working on a solution, I just set the Layout-height to 60 dp, after that everything Looks alright
Darius Wolkewitz

-----Ursprüngliche Nachricht-----
Von: Schmitt-Florian <notifications@github.com>
Gesendet: Freitag, 16. Juni 2017 15:06
An: Schmitt-Florian/SchoolPlanner <SchoolPlanner@noreply.github.com>
Cc: Darius <dww99@web.de>; Assign <assign@noreply.github.com>
Betreff: Re: [Schmitt-Florian/SchoolPlanner] design schedule (#17)

ok

**Comment by DWolkewitz** [comment]
what do you think @Schmitt-Florian

**Comment by Schmitt-Florian** [comment]
it's way better than before. Is it possible to do something similar to the length of the buttons, so Subjects with longer names can be displayed?

**Comment by DWolkewitz** [comment]
It will assimilate to it I think
Darius WolkewitzAm 16.06.17, 18:00, Schmitt-Florian <notifications@github.com> schrieb:
it's way better than before. Is it possible to do something similar to the length of the buttons, so Subjects with longer names can be displayed

**Comment by DWolkewitz** [comment]
But I would rather work with abbreviations
Darius WolkewitzAm 16.06.17, 18:00, Schmitt-Florian <notifications@github.com> schrieb:
it's way better than before. Is it possible to do something similar to the length of the buttons, so Subjects with longer names can be displayed

**Comment by Schmitt-Florian** [comment]
done
