### ISSUE TITLE
RawQuery Issue

### ISSUE THREAD

**Issue by DWolkewitz** [Schmitt-Florian/SchoolPlanner#24]
Can not get Gregorian Date from DB!
Method : getExamAtId

**Comment by Schmitt-Florian** [comment]
I'm not sure what exactly is the problem.
Something like "doesn't work" isn't a good description, but maybe it was fixed it in 671e803649d6856bdb29f0dd6255e368eea5bc65 already. If not please provide more information

**Comment by DWolkewitz** [comment]
`but maybe it was fixed it in 671e803 already.`
Was kind of, I had problems with the Gregorian Calender when I wanted to insert that data type in the db but you replaced it by a String...
So it's not exactly resolved but the problem doesn't exist anymore
