### ISSUE TITLE
write test cases for database

### ISSUE THREAD

**Issue by Schmitt-Florian** [Schmitt-Florian/SchoolPlanner#25]
I started with it in 1a55f3931fc525987944155babf3528342a14c8f , but due my occupation with the database class itself it would be rather nice if @DWolkewitz could take care of it. I think for now it would be good to have like three tests for each object similar to the ones i wrote for the Subjects. But feel free to modify and add other tests as well

**Comment by DWolkewitz** [comment]
Alright! 
Shall I test the different methods like delete or update aswell?
Do you need any other help with the database?

**Comment by Schmitt-Florian** [comment]
> Shall I test the different methods like delete or update aswell?
Do you need any other help with the database?

That would be very nice, but isn't as important as the for insert and get.
at the moment I don't need help with the database, but thanks for you offer.

**Comment by DWolkewitz** [comment]
Done writing the get and insert test cases
https://github.com/Schmitt-Florian/SchoolPlanner/commit/3243615b3f2175caeece80a9184bf7f77275c41e

**Comment by Schmitt-Florian** [comment]
I recently checked it and it seemed fine, but the testcases aren't able to be executed properly. I think it could be so, because the database needs some kind of "real" context to work with, so you maybe make it to run on a virtual device to work right.

**Comment by Schmitt-Florian** [comment]
probably not going to fix it in the next time, cause testcases are great but it's to much work to fix this, so we're returning to manualy testing the code
