### ISSUE TITLE
design exams screen

### ISSUE THREAD

**Issue by NatiBckr** [Schmitt-Florian/SchoolPlanner#27]
todo

**Comment by NatiBckr** [comment]
started working on it

**Comment by Schmitt-Florian** [comment]
are u really sure, that this is done? I took a look at it and it seemed to not be clear to use

**Comment by NatiBckr** [comment]
no I am not sure whether it is clear to use but I also don't really know what could be missing

**Comment by Schmitt-Florian** [comment]
passive until resolved question how to add a new exam

**Comment by Schmitt-Florian** [comment]
question resolved by #34 , so this is done now
