### ISSUE TITLE
Return to actual fragment after perspectivity changed

### ISSUE THREAD

**Issue by Schmitt-Florian** [Schmitt-Florian/SchoolPlanner#51]

**Comment by Schmitt-Florian** [comment]
just fmi, how's it going?

**Comment by DWolkewitz** [comment]
Done😎
Darius WolkewitzAm 30.05.17, 18:56, Schmitt-Florian <notifications@github.com> schrieb:
just fmi, how's it going?

**Comment by Schmitt-Florian** [comment]
would it be possible to push your code, so we can use it?

**Comment by DWolkewitz** [comment]
It is already, main activity
Darius WolkewitzAm 30.05.17, 23:33, Schmitt-Florian <notifications@github.com> schrieb:
would it be possible to push your code, so we can use it?
