### ISSUE TITLE
Issues with date selector

### ISSUE THREAD

**Issue by Schmitt-Florian** [Schmitt-Florian/SchoolPlanner#57]
there are a few errors with your new date selector:

1. ~~trying to save a exam/homework without having selected a date crashes the app~~
2. ~~if you open a already existing exam/homework which is not on the current date, the date selector nevertheless opens the dialog with the current date~~
3. ~~the selector dialog isn't supporting the different date formats~~

plus I have to highlight some coding style related flaws:

1.  those strings in the strings.xml which are beginning with "string_" should be the excact values to their keys, so something like `<string name="string_due_date">Select Date</string>` is not following the guidelines
2. to keep the code as readable as possible we should keep methods at a max of ca. 25 lines better 20
3. related to 2. the initialisation of the date selector should happen in a seperate private method which is called by the `initGUI();` method
4. if you change things in a method, keep an eye on the jdoc of the method to make sure it still represents the method, which is not the case at the `getDateFromMandatoryButton(View view, int id);` method in the GuiHelper class

**Comment by marlon-drolsbach** [comment]
I'm aware of these errors and I will try to fix them this evening.
And thanks for those "coding style related flaws"

**Comment by Schmitt-Florian** [comment]
Your welcome, that's perfect

**Comment by marlon-drolsbach** [comment]
-.-
