### ISSUE TITLE
DATABASE BUG

### ISSUE THREAD

**Issue by DWolkewitz** [Schmitt-Florian/SchoolPlanner#60]
When I create a new teacher and a new subject and click save it everything seems to be alright but as soon as I try to put the subject into the schedule the teacher and subject is gone. It is also not saved in the database (neither the teacher nor the subject)!

**Comment by Schmitt-Florian** [comment]
it's an known issue, everything is alright with the db. It happens b/c the database resets every time the app is started (this includes also switching between horizontal and vertical), try fix it by comenting out the code in the testing area in the mainactivity's `onCreate()` method

**Comment by DWolkewitz** [comment]
Ok so it's alright
